### ISSUE TITLE
Access WebPage Content

### ISSUE THREAD

**Issue by Cwiesen** [dint-dev/web_browser#2]
Currently, there doesn't seem to be a way to access webpage contents, such as innerHtml. I tried to use WebBrowserController's evaluateJavascript method, but as it returns a Future<void>, I'm not able to get data from it.

**Comment by terrier989** [comment]
This package does give you access to the underlying controller ([webview_flutter](https://pub.dev/packages/webview_flutter)), which has relevant methods.
