### ISSUE TITLE
Remove IFrameElement border on web.

### ISSUE THREAD

**Issue by artificerchris** [dint-dev/web_browser#9]
I've dug through the docs and code and can't seem to find a way to remove the border from the IFrame used in the web version, when I was embedding the frame myself I was able to set the `IFrameElement.style.border` property to `none` to remove the frame, is there any way to do this?

**Comment by tjholic** [comment]
I just added a line of code to web_browser library.

file : web_browser_impl_browser.dart

class WebBrowserState extends State<WebBrowser> {
  Widget? _builtWidget;
  html.IFrameElement? _element;
  bool _didUpdate = true;

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery
        .of(context)
        .size;
    if (_builtWidget == null) {
      // Construct iframe
      _element = html.IFrameElement();
      _element!.style.backgroundColor = 'white';
      **_element!.style.border = 'none';**
      ...
 }

**Comment by rjacwebagency** [comment]
UP any better solution ?

**Comment by artificerchris** [comment]
If all you need is the border gone, checkout my PR, I'm still not really sure why it wasn't just merged.
